apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-ext
spec:
  type: NodePort
  ports:
  - port: 6379
    targetPort: 6379
    nodePort: 32518
    name: client
  - port: 16379
    targetPort: 16379
    nodePort: 31239
    name: gossip
  selector:
    app: redis-cluster
